language: python
jobs:
  include:
    - name: "Python 3.9"
      python: 3.9
    - name: "Python 3.8"
      python: 3.8
    - name: "Python 3.7"
      python: 3.7
    - name: "Python 3.6"
      python: 3.6
cache:
  directories:
    - $HOME/.cache/pip

before_install:
- set -e
- python3 --version
- sudo apt-get install python3-pip flake8
- flake8 .
- pip3 install --upgrade setuptools pip
- pip3 install -r requirements.txt
- pip3 install --upgrade --index-url https://test.pypi.org/simple/ btrccts
- bash -c 'req="$(pip freeze | grep -v btrccts)" ; pip3 install hashin ; touch requirements.txt ; hashin ${req} ; cat requirements.txt'
- bash -c 'pip3 install pipdeptree ; pipdeptree -fl ; exit 0'

# Run algo to see all needed requirements are here
- python3 examples/print_time.py --start-date 2017-01-01 --end-date 2017-01-02
- pip3 install pycodestyle pyflakes
script:
- python3 -m unittest tests/unit/tests.py
- python3 -m unittest tests/integration/tests.py
